spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=susaladimahesh.ie@gmail.com
spring.mail.password=cdab muqn ifpb rbvj

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true